### ISSUE TITLE
Something wrong with split_annotation image.

### ISSUE THREAD

**Issue by Bang2hen1iu** [HuaijiaLin/AGSS-VOS#1]
Hello, thank you for releasing the code. I meet some problem when I follow the instruction. I've download the data.zip twice and unsqeeze it but unfortunately found that those image are empty which is all black. Would you please help checking?

**Comment by HuaijiaLin** [comment]
Can you provide the concrete path of the wrong image? If it is in the "youtube_vos" folder, it is reasonable. Because in "youtube_vos" dataset, not all the object is annotated in the same frame,  it is guaranteed that for any object in a video, there is always one frame annotated.

**Comment by Bang2hen1iu** [comment]
It sound weird but all of the annotation frames are empty. I have no idea whether the source is uploaded correctly since the size of data.zip is only 334MB.

**Comment by HuaijiaLin** [comment]
Does "the annotation frames are empty" mean "the images are all black"? It is because, in an annotated image, the pixel value denotes the object index. So if a video contains less than 10 objects, the pixel values are not larger than 10. Thus, the image looks all black but it really contains the annotation information.

**Comment by Bang2hen1iu** [comment]
Got it. Thanks for you reply.
